version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      observability:
        patterns:
          - "go.opentelemetry.io/*"
          - "github.com/prometheus/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
