// Package model defines the domain types consumed from Muninn's feature topics.
package model

import "time"

// FeatureEvent represents a computed feature event consumed from Muninn's
// Redpanda topics (e.g., features.obi.v1, features.vwap.v1).
//
// This mirrors the FeatureComputedEvent record emitted by Muninn's feature engine.
type FeatureEvent struct {
	EventID        string             `json:"eventId"`
	EventTime      time.Time          `json:"eventTime"`
	FeatureName    string             `json:"featureName"`
	FeatureVersion string             `json:"featureVersion"`
	Instrument     string             `json:"instrument"`
	WindowStart    time.Time          `json:"windowStart"`
	WindowEnd      time.Time          `json:"windowEnd"`
	SignalTimeMs   int64              `json:"signalTimeMs,omitempty"`
	Values         map[string]float64 `json:"values"`
}

// Side represents the direction of an order.
type Side int

const (
	Buy Side = iota
	Sell
)

func (s Side) String() string {
	switch s {
	case Buy:
		return "BUY"
	case Sell:
		return "SELL"
	default:
		return "UNKNOWN"
	}
}

// Liquidity classifies how an order interacts with the order book at fill
// time. A taker order crosses the spread (aggressive) and pays the taker fee;
// a maker order rests at the touch (passive) and pays the maker fee/rebate,
// filling only if the market subsequently trades through the resting level.
//
// The zero value is Taker, so any Order or Fill that does not set Liquidity
// keeps the original always-cross-the-spread behaviour.
type Liquidity int

const (
	// Taker is the default: cross the spread now and pay the taker fee.
	Taker Liquidity = iota
	// Maker rests at the touch and pays the maker fee/rebate, filling only on
	// a subsequent through-trade (adverse-selection model).
	Maker
)

func (l Liquidity) String() string {
	switch l {
	case Taker:
		return "TAKER"
	case Maker:
		return "MAKER"
	default:
		return "UNKNOWN"
	}
}

// Order represents a paper-trade order generated by a strategy.
type Order struct {
	Instrument string
	Side       Side
	Quantity   float64
	LimitPrice float64 // 0 = market order
	Reason     string  // human-readable strategy rationale
	Timestamp  time.Time

	// Liquidity selects the execution style for this order. The zero value
	// (Taker) preserves the historical cross-the-spread behaviour; Maker opts
	// into passive resting fills that only execute on a through-trade.
	Liquidity Liquidity
}

// Fill represents an execution of an order — either simulated by the paper
// executor or relayed from Sleipnir over the live fills topic.
//
// ExecutionID is a deterministic per-fill identity supplied by Sleipnir
// (REST submit / WS executionReport / boot reconciliation). The executor's
// dedup cache uses it to drop duplicate fills that arrive when the gateway
// reconciles a missed event on restart. Empty for paper-mode fills, which
// are produced exactly once per simulateFill call.
type Fill struct {
	OrderID         string
	ExecutionID     string
	Instrument      string
	Side            Side
	Quantity        float64
	FillPrice       float64
	TransactionCost float64
	SlippageBps     float64
	Timestamp       time.Time

	// Liquidity records whether this fill was a taker (crossed the spread) or a
	// maker (rested at the touch). Zero value is Taker, so existing fills and
	// every pre-maker code path keep their original classification.
	Liquidity Liquidity
}
