// Package model defines the domain types consumed from Muninn's feature topics.
package model

import "time"

// FeatureEvent represents a computed feature event consumed from Muninn's
// Redpanda topics (e.g., features.obi.v1, features.vwap.v1).
//
// This mirrors the FeatureComputedEvent record emitted by Muninn's feature engine.
type FeatureEvent struct {
	EventID        string            `json:"eventId"`
	EventTime      time.Time         `json:"eventTime"`
	FeatureName    string            `json:"featureName"`
	FeatureVersion string            `json:"featureVersion"`
	Instrument     string            `json:"instrument"`
	WindowStart    time.Time         `json:"windowStart"`
	WindowEnd      time.Time         `json:"windowEnd"`
	Values         map[string]float64 `json:"values"`
}

// Side represents the direction of an order.
type Side int

const (
	Buy Side = iota
	Sell
)

func (s Side) String() string {
	switch s {
	case Buy:
		return "BUY"
	case Sell:
		return "SELL"
	default:
		return "UNKNOWN"
	}
}

// Order represents a paper-trade order generated by a strategy.
type Order struct {
	Instrument string
	Side       Side
	Quantity   float64
	LimitPrice float64 // 0 = market order
	Reason     string  // human-readable strategy rationale
	Timestamp  time.Time
}

// Fill represents a simulated execution of an order.
type Fill struct {
	OrderID         string
	Instrument      string
	Side            Side
	Quantity        float64
	FillPrice       float64
	TransactionCost float64
	SlippageBps     float64
	Timestamp       time.Time
}
