package backtest

import (
	"fmt"
	"html/template"
	"math"
	"os"
	"strings"
	"time"

	"github.com/lgreene03/huginn/internal/model"
)

// ReportParams collects every value the HTML report template needs.
type ReportParams struct {
	Strategy    string
	ConfigPath  string
	DataPath    string
	InitialCash float64
	FinalValue  float64
	RealizedPnL float64
	TotalFills  int
	MaxDrawdown float64
	Sharpe      float64
	HitRate     float64
	Turnover    float64
	AvgHoldSec  float64
	Equity      []float64
	Fills       []model.Fill
	GeneratedAt time.Time

	// Buy-and-hold benchmark over the same window. BenchmarkValid is false
	// when no instrument in the stream was priceable (nothing to hold), in
	// which case the benchmark section is omitted from the report.
	BenchmarkValid       bool
	BenchmarkInstruments int
	StrategyTotalReturn  float64 // fractional, e.g. 0.05 = +5%
	BenchmarkTotalReturn float64 // fractional
	ExcessReturn         float64 // strategy − benchmark, fractional
	InformationRatio     float64 // mean active return / stddev of active return
}

// GenerateHTMLReport writes a self-contained HTML report to outputPath.
// The file has no external dependencies — all CSS and chart data are inlined.
func GenerateHTMLReport(p ReportParams, outputPath string) error {
	svg := buildEquitySVG(p.Equity, p.InitialCash)
	fillRows := buildFillRows(p.Fills)

	data := templateData{
		ReportParams: p,
		SVGChart:     template.HTML(svg), //nolint:gosec // fully trusted, generated by us
		FillRows:     fillRows,
	}

	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("create report file: %w", err)
	}
	defer func() { _ = f.Close() }()

	return htmlReportTemplate().Execute(f, data)
}

type templateData struct {
	ReportParams
	SVGChart template.HTML
	FillRows []fillRow
}

type fillRow struct {
	Timestamp       string
	Instrument      string
	Side            string
	Quantity        string
	FillPrice       string
	TransactionCost string
}

func buildFillRows(fills []model.Fill) []fillRow {
	const maxRows = 500
	rows := make([]fillRow, 0, len(fills))
	for i, f := range fills {
		if i >= maxRows {
			break
		}
		rows = append(rows, fillRow{
			Timestamp:       f.Timestamp.Format("2006-01-02 15:04:05"),
			Instrument:      f.Instrument,
			Side:            f.Side.String(),
			Quantity:        fmt.Sprintf("%.6f", f.Quantity),
			FillPrice:       fmt.Sprintf("%.4f", f.FillPrice),
			TransactionCost: fmt.Sprintf("%.6f", f.TransactionCost),
		})
	}
	return rows
}

// buildEquitySVG produces an inline <svg> element for the equity curve.
// Returns a placeholder when there are fewer than two data points.
func buildEquitySVG(equity []float64, initialCash float64) string {
	if len(equity) < 2 {
		return `<p class="chart-empty">Not enough equity samples to draw a curve.</p>`
	}

	const (
		w       = 800
		h       = 220
		padLeft = 60
		padBot  = 30
		padTop  = 20
		padRt   = 20
	)

	chartW := float64(w - padLeft - padRt)
	chartH := float64(h - padTop - padBot)

	minV, maxV := equity[0], equity[0]
	for _, v := range equity {
		if v < minV {
			minV = v
		}
		if v > maxV {
			maxV = v
		}
	}
	spread := maxV - minV
	if spread == 0 {
		spread = 1
	}

	n := len(equity)
	pts := make([]string, 0, n)
	for i, v := range equity {
		x := float64(padLeft) + float64(i)/float64(n-1)*chartW
		y := float64(padTop) + (1-(v-minV)/spread)*chartH
		pts = append(pts, fmt.Sprintf("%.1f,%.1f", x, y))
	}
	polyline := strings.Join(pts, " ")

	// Filled area beneath the curve.
	fillColour := "#1a3a1a"
	if equity[len(equity)-1] < initialCash {
		fillColour = "#3a1a1a"
	}
	areaPoints := polyline +
		fmt.Sprintf(" %.1f,%.1f %.1f,%.1f",
			float64(padLeft)+chartW, float64(padTop)+chartH,
			float64(padLeft), float64(padTop)+chartH)

	// Baseline at initial cash level.
	baselineY := float64(padTop) + (1-(initialCash-minV)/spread)*chartH

	// Y-axis tick labels.
	yTop := fmt.Sprintf("%.0f", maxV)
	yMid := fmt.Sprintf("%.0f", (minV+maxV)/2)
	yBot := fmt.Sprintf("%.0f", minV)

	xMid := float64(padLeft) + chartW/2
	xEnd := float64(padLeft) + chartW

	return fmt.Sprintf(
		`<svg viewBox="0 0 %d %d" width="%d" height="%d" xmlns="http://www.w3.org/2000/svg">`+
			`<rect x="%d" y="%d" width="%.0f" height="%.0f" fill="#111" rx="4"/>`+
			`<polygon points="%s" fill="%s" opacity="0.4"/>`+
			`<line x1="%d" y1="%.1f" x2="%.1f" y2="%.1f" stroke="#555" stroke-width="1" stroke-dasharray="4 3"/>`+
			`<polyline points="%s" fill="none" stroke="#00e5a0" stroke-width="2"/>`+
			`<text x="%d" y="%.1f" fill="#888" font-size="10" text-anchor="end">%s</text>`+
			`<text x="%d" y="%.1f" fill="#888" font-size="10" text-anchor="end">%s</text>`+
			`<text x="%d" y="%.1f" fill="#888" font-size="10" text-anchor="end">%s</text>`+
			`<text x="%d" y="%.1f" fill="#888" font-size="10" text-anchor="middle">0</text>`+
			`<text x="%.1f" y="%.1f" fill="#888" font-size="10" text-anchor="middle">%d</text>`+
			`<text x="%.1f" y="%.1f" fill="#888" font-size="10" text-anchor="end">%d</text>`+
			`</svg>`,
		w, h, w, h,
		padLeft, padTop, chartW, chartH,
		areaPoints, fillColour,
		padLeft, baselineY, float64(padLeft)+chartW, baselineY,
		polyline,
		padLeft-4, float64(padTop)+5, yTop,
		padLeft-4, float64(padTop)+chartH/2+4, yMid,
		padLeft-4, float64(padTop)+chartH-2, yBot,
		padLeft, float64(padTop)+chartH+math.Round(float64(padBot)*0.6),
		xMid, float64(padTop)+chartH+math.Round(float64(padBot)*0.6), n/2,
		xEnd, float64(padTop)+chartH+math.Round(float64(padBot)*0.6), n-1,
	)
}

func htmlReportTemplate() *template.Template {
	return template.Must(template.New("report").Funcs(template.FuncMap{
		"mulF":  func(a, b float64) float64 { return a * b },
		"lower": strings.ToLower,
		"fmtDuration": func(secs float64) string {
			if secs == 0 {
				return "n/a"
			}
			if secs < 60 {
				return fmt.Sprintf("%.0fs", secs)
			}
			if secs < 3600 {
				return fmt.Sprintf("%.1fm", secs/60)
			}
			return fmt.Sprintf("%.1fh", secs/3600)
		},
		"gt": func(a, b int) bool { return a > b },
	}).Parse(reportHTML))
}

const reportHTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Huginn Backtest — {{.Strategy}}</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:ui-monospace,Menlo,monospace;background:#0d0d0d;color:#d0d0d0;padding:24px;font-size:13px}
h1{color:#e8e8e8;font-size:20px;margin-bottom:4px}
.meta{color:#666;margin-bottom:24px;font-size:12px}
section{margin-bottom:28px}
h2{color:#aaa;font-size:13px;text-transform:uppercase;letter-spacing:.08em;border-bottom:1px solid #222;padding-bottom:6px;margin-bottom:12px}
.stats-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:12px}
.stat{background:#141414;border:1px solid #222;border-radius:6px;padding:12px}
.stat-label{color:#666;font-size:11px;margin-bottom:4px}
.stat-value{font-size:18px;font-weight:700;color:#e8e8e8}
.stat-value.pos{color:#00e5a0}
.stat-value.neg{color:#ff5c5c}
.chart-wrap{background:#111;border:1px solid #222;border-radius:6px;padding:12px;overflow-x:auto}
.chart-empty{color:#555;padding:12px}
table{width:100%;border-collapse:collapse;font-size:12px}
thead tr{background:#161616;color:#888;text-transform:uppercase;font-size:10px;letter-spacing:.06em}
th,td{padding:6px 10px;text-align:right;border-bottom:1px solid #1a1a1a}
th:first-child,td:first-child{text-align:left}
tr:hover td{background:#141414}
.buy{color:#00e5a0}
.sell{color:#ff5c5c}
.trunc{color:#555;font-size:11px;margin-top:8px}
</style>
</head>
<body>
<h1>Huginn Backtest — {{.Strategy}}</h1>
<p class="meta">Generated {{.GeneratedAt.Format "2006-01-02 15:04:05 UTC"}} &middot; data: {{.DataPath}} &middot; config: {{.ConfigPath}}</p>

<section>
<h2>Performance Summary</h2>
<div class="stats-grid">
  <div class="stat"><div class="stat-label">Initial Cash</div><div class="stat-value">{{printf "%.2f" .InitialCash}}</div></div>
  <div class="stat"><div class="stat-label">Final Value</div><div class="stat-value {{if ge .FinalValue .InitialCash}}pos{{else}}neg{{end}}">{{printf "%.2f" .FinalValue}}</div></div>
  <div class="stat"><div class="stat-label">Realized PnL</div><div class="stat-value {{if ge .RealizedPnL 0.0}}pos{{else}}neg{{end}}">{{printf "%.4f" .RealizedPnL}}</div></div>
  <div class="stat"><div class="stat-label">Total Fills</div><div class="stat-value">{{.TotalFills}}</div></div>
  <div class="stat"><div class="stat-label">Sharpe Ratio</div><div class="stat-value {{if ge .Sharpe 0.0}}pos{{else}}neg{{end}}">{{printf "%.4f" .Sharpe}}</div></div>
  <div class="stat"><div class="stat-label">Max Drawdown</div><div class="stat-value neg">{{printf "%.2f" (mulF .MaxDrawdown 100.0)}}%</div></div>
  <div class="stat"><div class="stat-label">Hit Rate</div><div class="stat-value">{{printf "%.1f" (mulF .HitRate 100.0)}}%</div></div>
  <div class="stat"><div class="stat-label">Turnover</div><div class="stat-value">{{printf "%.2f" .Turnover}}x</div></div>
  <div class="stat"><div class="stat-label">Avg Hold</div><div class="stat-value">{{fmtDuration .AvgHoldSec}}</div></div>
</div>
</section>

{{if .BenchmarkValid}}
<section>
<h2>Buy-and-Hold Benchmark ({{.BenchmarkInstruments}} instrument{{if gt .BenchmarkInstruments 1}}s{{end}})</h2>
<div class="stats-grid">
  <div class="stat"><div class="stat-label">Strategy Return</div><div class="stat-value {{if ge .StrategyTotalReturn 0.0}}pos{{else}}neg{{end}}">{{printf "%+.2f" (mulF .StrategyTotalReturn 100.0)}}%</div></div>
  <div class="stat"><div class="stat-label">Buy &amp; Hold Return</div><div class="stat-value {{if ge .BenchmarkTotalReturn 0.0}}pos{{else}}neg{{end}}">{{printf "%+.2f" (mulF .BenchmarkTotalReturn 100.0)}}%</div></div>
  <div class="stat"><div class="stat-label">Excess Return</div><div class="stat-value {{if ge .ExcessReturn 0.0}}pos{{else}}neg{{end}}">{{printf "%+.2f" (mulF .ExcessReturn 100.0)}}%</div></div>
  <div class="stat"><div class="stat-label">Information Ratio</div><div class="stat-value {{if ge .InformationRatio 0.0}}pos{{else}}neg{{end}}">{{printf "%.4f" .InformationRatio}}</div></div>
</div>
</section>
{{end}}

<section>
<h2>Equity Curve ({{len .Equity}} daily samples)</h2>
<div class="chart-wrap">{{.SVGChart}}</div>
</section>

<section>
<h2>Fills ({{len .FillRows}} shown{{if gt .TotalFills 500}} of {{.TotalFills}} — truncated at 500{{end}})</h2>
<table>
<thead><tr><th>Time</th><th>Instrument</th><th>Side</th><th>Qty</th><th>Price</th><th>Cost</th></tr></thead>
<tbody>
{{range .FillRows}}<tr>
  <td>{{.Timestamp}}</td>
  <td>{{.Instrument}}</td>
  <td class="{{lower .Side}}">{{.Side}}</td>
  <td>{{.Quantity}}</td>
  <td>{{.FillPrice}}</td>
  <td>{{.TransactionCost}}</td>
</tr>{{end}}
</tbody>
</table>
{{if gt .TotalFills 500}}<p class="trunc">Showing first 500 of {{.TotalFills}} fills. See data/backtest_trades.jsonl for the full list.</p>{{end}}
</section>
</body>
</html>
`
