package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	FeaturesConsumedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "huginn_features_consumed_total",
		Help: "Total number of features consumed from Muninn",
	})
	OrdersGeneratedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "huginn_orders_generated_total",
		Help: "Total number of orders generated by strategies",
	})
	FillsExecutedTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "huginn_fills_executed_total",
		Help: "Total number of simulated order fills executed",
	})
	PortfolioCash = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "huginn_portfolio_cash",
		Help: "Current available cash in the portfolio",
	})
	PortfolioRealizedPnL = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "huginn_portfolio_realized_pnl",
		Help: "Current realized PnL of the portfolio",
	})
	PortfolioTotalValue = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "huginn_portfolio_total_value",
		Help: "Current total value of the portfolio (cash + positions)",
	})
)
